# Generated by Django 3.1.5 on 2021-01-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSellerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('brand', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclebrand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('modification', models.CharField(blank=True, max_length=128)),
                ('year_manufacture', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('quantity_owner', models.CharField(max_length=2)),
                ('quantity_doors', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclebodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclebrand')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='get_car_info.city')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclecolor')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclecondition')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehicledrive')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehicleenginetype')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehicleequipment')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclegeneration')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclemodel')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='get_car_info.region')),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclesellertype')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehicletransmission')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.vehiclewheel')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_car_info.region'),
        ),
    ]
