# Generated by Django 3.1.5 on 2021-03-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_car_info', '0005_auto_20210128_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['name']},
        ),
    ]
